import { EndpointDefinition } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// ENDPOINT CATALOG
//
// This file is the single source of truth for all pre-registered API endpoints.
// To add a new endpoint, append an entry to the ENDPOINTS array below.
//
// Each entry maps to a human-readable alias shown in the Grafana query editor.
// Users never see the raw API path — they only see the alias and description.
//
// HOW TO UPDATE WHEN REAL API SPECS ARE AVAILABLE:
//   1. Replace the `path` values with the real endpoint paths from your APIs.
//   2. Update the `params` array with actual query/path/body parameters.
//   3. Update `resultPath` to point to the array or value in the JSON response.
//   4. Adjust `alias` and `description` as needed for clarity.
// ─────────────────────────────────────────────────────────────────────────────

export const ENDPOINTS: EndpointDefinition[] = [

  // ── Energy Efficiency Service ──────────────────────────────────────────────
  {
    id: 'ee-buildings-list',
    service: 'energy-efficiency',
    alias: 'List Buildings',
    description: 'Retrieve all buildings with their energy efficiency metadata.',
    method: 'GET',
    path: '/api/v1/buildings',
    resultPath: 'data',
    params: [
      {
        name: 'page',
        label: 'Page',
        in: 'query',
        required: false,
        description: 'Page number for pagination',
        type: 'number',
        example: '1',
      },
      {
        name: 'pageSize',
        label: 'Page Size',
        in: 'query',
        required: false,
        description: 'Number of results per page',
        type: 'number',
        example: '50',
      },
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Filter records from this timestamp',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'Filter records up to this timestamp',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
    ],
  },
  {
    id: 'ee-building-detail',
    service: 'energy-efficiency',
    alias: 'Get Building',
    description: 'Retrieve detailed information for a single building by ID.',
    method: 'GET',
    path: '/api/v1/buildings/{buildingId}',
    resultPath: 'data',
    params: [
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the building',
        type: 'string',
        example: 'building-001',
      },
    ],
  },
  {
    id: 'ee-building-energy-consumption',
    service: 'energy-efficiency',
    alias: 'Building Energy Consumption',
    description: 'Time-series energy consumption data for a specific building.',
    method: 'GET',
    path: '/api/v1/buildings/{buildingId}/energy-consumption',
    resultPath: 'data',
    params: [
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the building',
        type: 'string',
        example: 'building-001',
      },
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Start of the time range',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'End of the time range',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
      {
        name: 'interval',
        label: 'Interval',
        in: 'query',
        required: false,
        description: 'Aggregation interval (e.g. 1h, 1d, 1w)',
        type: 'string',
        example: '1h',
      },
    ],
  },
  {
    id: 'ee-building-efficiency-score',
    service: 'energy-efficiency',
    alias: 'Building Efficiency Score',
    description: 'Current energy efficiency score (EPC/label) for a building.',
    method: 'GET',
    path: '/api/v1/buildings/{buildingId}/efficiency-score',
    resultPath: 'data',
    params: [
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the building',
        type: 'string',
        example: 'building-001',
      },
    ],
  },
  {
    id: 'ee-meters-list',
    service: 'energy-efficiency',
    alias: 'List Meters',
    description: 'List all energy meters associated with a building.',
    method: 'GET',
    path: '/api/v1/buildings/{buildingId}/meters',
    resultPath: 'data',
    params: [
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the building',
        type: 'string',
        example: 'building-001',
      },
      {
        name: 'type',
        label: 'Meter Type',
        in: 'query',
        required: false,
        description: 'Filter by meter type (electricity, gas, water, heat)',
        type: 'string',
        example: 'electricity',
      },
    ],
  },
  {
    id: 'ee-meter-readings',
    service: 'energy-efficiency',
    alias: 'Meter Readings',
    description: 'Time-series readings for a specific meter.',
    method: 'GET',
    path: '/api/v1/meters/{meterId}/readings',
    resultPath: 'data',
    params: [
      {
        name: 'meterId',
        label: 'Meter ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the meter',
        type: 'string',
        example: 'meter-001',
      },
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Start of the time range',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'End of the time range',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
      {
        name: 'interval',
        label: 'Interval',
        in: 'query',
        required: false,
        description: 'Aggregation interval (e.g. 1h, 1d, 1w)',
        type: 'string',
        example: '1h',
      },
    ],
  },
  {
    id: 'ee-efficiency-analysis',
    service: 'energy-efficiency',
    alias: 'Run Efficiency Analysis',
    description: 'Submit an analysis request for a building over a period.',
    method: 'POST',
    path: '/api/v1/buildings/{buildingId}/analysis',
    resultPath: 'data',
    params: [
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the building',
        type: 'string',
        example: 'building-001',
      },
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'body',
        required: true,
        description: 'Start of the analysis period',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'body',
        required: true,
        description: 'End of the analysis period',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
    ],
  },

  // ── Asset Service ──────────────────────────────────────────────────────────
  {
    id: 'asset-list',
    service: 'asset',
    alias: 'List Assets',
    description: 'Retrieve all registered assets.',
    method: 'GET',
    path: '/api/v1/assets',
    resultPath: 'data',
    params: [
      {
        name: 'page',
        label: 'Page',
        in: 'query',
        required: false,
        description: 'Page number for pagination',
        type: 'number',
        example: '1',
      },
      {
        name: 'pageSize',
        label: 'Page Size',
        in: 'query',
        required: false,
        description: 'Number of results per page',
        type: 'number',
        example: '50',
      },
      {
        name: 'type',
        label: 'Asset Type',
        in: 'query',
        required: false,
        description: 'Filter by asset type',
        type: 'string',
        example: 'hvac',
      },
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'query',
        required: false,
        description: 'Filter assets by building',
        type: 'string',
        example: 'building-001',
      },
    ],
  },
  {
    id: 'asset-detail',
    service: 'asset',
    alias: 'Get Asset',
    description: 'Retrieve full details for a single asset by ID.',
    method: 'GET',
    path: '/api/v1/assets/{assetId}',
    resultPath: 'data',
    params: [
      {
        name: 'assetId',
        label: 'Asset ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the asset',
        type: 'string',
        example: 'asset-001',
      },
    ],
  },
  {
    id: 'asset-types-list',
    service: 'asset',
    alias: 'List Asset Types',
    description: 'Retrieve all supported asset types and their metadata.',
    method: 'GET',
    path: '/api/v1/asset-types',
    resultPath: 'data',
    params: [],
  },
  {
    id: 'asset-history',
    service: 'asset',
    alias: 'Asset Event History',
    description: 'Historical events (maintenance, state changes) for an asset.',
    method: 'GET',
    path: '/api/v1/assets/{assetId}/history',
    resultPath: 'data',
    params: [
      {
        name: 'assetId',
        label: 'Asset ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the asset',
        type: 'string',
        example: 'asset-001',
      },
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Start of the history range',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'End of the history range',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
    ],
  },
  {
    id: 'asset-telemetry',
    service: 'asset',
    alias: 'Asset Telemetry',
    description: 'Live and historical sensor telemetry for an asset.',
    method: 'GET',
    path: '/api/v1/assets/{assetId}/telemetry',
    resultPath: 'data',
    params: [
      {
        name: 'assetId',
        label: 'Asset ID',
        in: 'path',
        required: true,
        description: 'Unique identifier of the asset',
        type: 'string',
        example: 'asset-001',
      },
      {
        name: 'metric',
        label: 'Metric',
        in: 'query',
        required: false,
        description: 'Specific metric to retrieve (e.g. temperature, pressure)',
        type: 'string',
        example: 'temperature',
      },
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Start of the time range',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'End of the time range',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
    ],
  },
  {
    id: 'asset-search',
    service: 'asset',
    alias: 'Search Assets',
    description: 'Full-text search across assets with optional filters.',
    method: 'POST',
    path: '/api/v1/assets/search',
    resultPath: 'data',
    params: [
      {
        name: 'query',
        label: 'Search Query',
        in: 'body',
        required: false,
        description: 'Free-text search string',
        type: 'string',
        example: 'boiler',
      },
      {
        name: 'type',
        label: 'Asset Type',
        in: 'body',
        required: false,
        description: 'Filter by asset type',
        type: 'string',
        example: 'hvac',
      },
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'body',
        required: false,
        description: 'Limit search to a specific building',
        type: 'string',
        example: 'building-001',
      },
    ],
  },

  // ── CO2 Service ────────────────────────────────────────────────────────────
  {
    id: 'co2-emissions-list',
    service: 'co2',
    alias: 'CO2 Emissions',
    description: 'Time-series CO2 emission data across all sources or filtered.',
    method: 'GET',
    path: '/api/v1/emissions',
    resultPath: 'data',
    params: [
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Start of the time range',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'End of the time range',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'query',
        required: false,
        description: 'Filter emissions by building',
        type: 'string',
        example: 'building-001',
      },
      {
        name: 'scope',
        label: 'Scope',
        in: 'query',
        required: false,
        description: 'GHG Protocol scope: 1, 2, or 3',
        type: 'string',
        example: '2',
      },
      {
        name: 'interval',
        label: 'Interval',
        in: 'query',
        required: false,
        description: 'Aggregation interval (e.g. 1h, 1d, 1M)',
        type: 'string',
        example: '1d',
      },
    ],
  },
  {
    id: 'co2-emissions-summary',
    service: 'co2',
    alias: 'CO2 Emissions Summary',
    description: 'Aggregated CO2 totals grouped by source, building, or period.',
    method: 'GET',
    path: '/api/v1/emissions/summary',
    resultPath: 'data',
    params: [
      {
        name: 'from',
        label: 'From (ISO8601)',
        in: 'query',
        required: false,
        description: 'Start of the period',
        type: 'datetime',
        example: '2024-01-01T00:00:00Z',
      },
      {
        name: 'to',
        label: 'To (ISO8601)',
        in: 'query',
        required: false,
        description: 'End of the period',
        type: 'datetime',
        example: '2024-12-31T23:59:59Z',
      },
      {
        name: 'groupBy',
        label: 'Group By',
        in: 'query',
        required: false,
        description: 'Dimension to group by: building, scope, source, month',
        type: 'string',
        example: 'building',
      },
    ],
  },
  {
    id: 'co2-factors',
    service: 'co2',
    alias: 'Emission Factors',
    description: 'Retrieve current CO2 emission conversion factors by energy carrier.',
    method: 'GET',
    path: '/api/v1/emission-factors',
    resultPath: 'data',
    params: [
      {
        name: 'country',
        label: 'Country Code',
        in: 'query',
        required: false,
        description: 'ISO 3166-1 alpha-2 country code for region-specific factors',
        type: 'string',
        example: 'NL',
      },
      {
        name: 'year',
        label: 'Year',
        in: 'query',
        required: false,
        description: 'Year for which to retrieve factors',
        type: 'number',
        example: '2024',
      },
    ],
  },
  {
    id: 'co2-calculate',
    service: 'co2',
    alias: 'Calculate CO2',
    description: 'Calculate CO2 equivalent for a given energy consumption and carrier.',
    method: 'POST',
    path: '/api/v1/emissions/calculate',
    resultPath: 'data',
    params: [
      {
        name: 'energyKwh',
        label: 'Energy (kWh)',
        in: 'body',
        required: true,
        description: 'Energy consumption in kilowatt-hours',
        type: 'number',
        example: '10000',
      },
      {
        name: 'carrier',
        label: 'Energy Carrier',
        in: 'body',
        required: true,
        description: 'Type of energy carrier (electricity, gas, heat)',
        type: 'string',
        example: 'electricity',
      },
      {
        name: 'country',
        label: 'Country Code',
        in: 'body',
        required: false,
        description: 'ISO 3166-1 alpha-2 country code',
        type: 'string',
        example: 'NL',
      },
      {
        name: 'year',
        label: 'Year',
        in: 'body',
        required: false,
        description: 'Reference year for emission factors',
        type: 'number',
        example: '2024',
      },
    ],
  },
  {
    id: 'co2-targets',
    service: 'co2',
    alias: 'CO2 Reduction Targets',
    description: 'Retrieve defined CO2 reduction targets and progress against them.',
    method: 'GET',
    path: '/api/v1/targets',
    resultPath: 'data',
    params: [
      {
        name: 'buildingId',
        label: 'Building ID',
        in: 'query',
        required: false,
        description: 'Filter targets by building',
        type: 'string',
        example: 'building-001',
      },
    ],
  },
  {
    id: 'co2-reports',
    service: 'co2',
    alias: 'CO2 Reports',
    description: 'List generated CO2 compliance and sustainability reports.',
    method: 'GET',
    path: '/api/v1/reports',
    resultPath: 'data',
    params: [
      {
        name: 'year',
        label: 'Year',
        in: 'query',
        required: false,
        description: 'Filter reports by year',
        type: 'number',
        example: '2024',
      },
    ],
  },
];

export const SERVICE_LABELS: Record<string, string> = {
  'energy-efficiency': 'Energy Efficiency',
  asset: 'Asset Management',
  co2: 'CO2 & Emissions',
};

export function getEndpointById(id: string): EndpointDefinition | undefined {
  return ENDPOINTS.find((e) => e.id === id);
}

export function getEndpointsByService(service: string): EndpointDefinition[] {
  return ENDPOINTS.filter((e) => e.service === service);
}
